# Template for secrets - DO NOT commit actual secrets
DATABASE_URL: "postgresql://username@cluster-endpoint:5432/aistackdb"
SUPABASE_URL: "https://your-project.supabase.co"
SUPABASE_ANON_KEY: "your_anon_key_here"
SUPABASE_SERVICE_KEY: "your_service_key_here"
SUPABASE_JWT_SECRET: "your_jwt_secret_here"
STRIPE_SECRET_KEY: "sk_test_your_stripe_key"
STRIPE_PUBLISHABLE_KEY: "pk_test_your_stripe_key"
STRIPE_WEBHOOK_SECRET: "whsec_your_webhook_secret"
DIGITALOCEAN_TOKEN: "dop_v1_your_token_here"
FRONTEND_URL: "https://yourdomain.com"
BACKEND_URL: "https://api.yourdomain.com"
