# .github/workflows/frontend-deploy.yml

name: Deploy Frontend to Vercel

on:
 push:
   branches: [main, staging]
   paths:
     - 'frontend/**'
     - '.github/workflows/frontend-deploy.yml'
 workflow_dispatch:

env:
 NODE_VERSION: '18'

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: ${{ env.NODE_VERSION }}
         cache: 'npm'
         cache-dependency-path: frontend/package-lock.json

     - name: Install dependencies
       run: |
         cd frontend
         npm ci

     - name: Run linting
       run: |
         cd frontend
         npm run lint

     - name: Run type checking
       run: |
         cd frontend
         npm run type-check

     - name: Run tests
       run: |
         cd frontend
         npm run test

 deploy:
   needs: test
   runs-on: ubuntu-latest
   environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
   
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: ${{ env.NODE_VERSION }}
         cache: 'npm'
         cache-dependency-path: frontend/package-lock.json

     - name: Install dependencies
       run: |
         cd frontend
         npm ci

     - name: Build project
       run: |
         cd frontend
         npm run build
       env:
         NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
         NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
         NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
         NEXT_PUBLIC_API_URL: ${{ secrets.BACKEND_URL }}

     - name: Deploy to Vercel
       uses: amondnet/vercel-action@v25
       with:
         vercel-token: ${{ secrets.VERCEL_TOKEN }}
         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
         working-directory: ./frontend
         vercel-args: '--prod'
       env:
         NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
         NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
         NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
         NEXT_PUBLIC_API_URL: ${{ secrets.BACKEND_URL }}

 post-deploy:
   needs: deploy
   runs-on: ubuntu-latest
   if: success() && github.ref == 'refs/heads/main'
   
   steps:
     - name: Deployment summary
       run: |
         echo "🎉 Frontend deployed to Vercel successfully!"
         echo "Check your Vercel dashboard for the live URL"

     - name: Send Slack notification
       if: always()
       uses: 8398a7/action-slack@v3
       with:
         status: ${{ job.status }}
         channel: '#deployments'
         text: |
           Frontend deployment to Vercel ${{ job.status }}!
           Commit: ${{ github.sha }}
           Author: ${{ github.actor }}
       env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}